### ISSUE TITLE
El blog no funciona en Safari

### ISSUE THREAD

**Issue by edvilme** [Ctrl-Alt-Tec/Figura#7]
Isabel usa Safari en Mac y no le aparece el contenido del blog. Desde el iPad tampoco lo puedo ver. 
El sitio hace una llamada HTTPS a la [API de Ctrl Alt Tec](https://github.com/ctrl-alt-tec/api), supongo que debe ir por ahí.
No tengo Mac, entonces no puedo debuggear

**Comment by LordFritos** [comment]
Justo estaba revisando un poco del altBlog.js porque tarda un poco. Cuando te metes a un post como que twichea un poco y luego ya aparece el post (BTW se te fue un "Lorem ipsum" jejeje)

**Comment by edvilme** [comment]
F. Mejor que use chrome y yap jajajajaja

**Comment by LordFritos** [comment]
Looool
